# Generated by Django 5.0 on 2024-03-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
